services:
    web:
        container_name: gamespace_web
        build:
            context: .
            target: prod
        restart: always
        environment:
            DATABASE_URL: ${DATABASE_URL}
            WEB_HOST_PORT: ${WEB_HOST_PORT}
            WEB_URL_ROOT: ${WEB_URL_ROOT}
        ports:
            - ${WEB_HOST_PORT}:${WEB_DOCKER_PORT}
        links:
            - mariadb
        stdin_open: true
        tty: true

    mariadb:
        container_name: gamespace_db
        image: mariadb:11.6.2
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_HOST_PORT}:${DB_DOCKER_PORT}
        volumes:
            - ./.mariadb:/var/lib/mysql

    adminer:
        container_name: gamespace_adminer
        image: adminer:latest
        environment:
            ADMINER_DEFAULT_SERVER: ${DB_HOST}
        ports:
            - ${ADM_HOST_PORT}:${ADM_DOCKER_PORT}
        depends_on:
            - mariadb
        restart: always
