services:
    gamespace_web:
        container_name: gamespace_web_dev
        build:
            context: .
            target: dev
        restart: always
        environment:
            DATABASE_URL: ${DATABASE_URL}
            WEB_HOST_PORT: ${WEB_HOST_PORT}
            WEB_URL_ROOT: ${WEB_URL_ROOT}
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        ports:
            - ${WEB_HOST_PORT}:${WEB_DOCKER_PORT}
        links:
            - ${DB_HOST}
        depends_on:
            - ${DB_HOST}

    gamespace_db:
        container_name: gamespace_db_dev
        image: mariadb:11.6.2
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            TZ: "Europe/Paris"
        ports:
            - ${DB_HOST_PORT}:${DB_DOCKER_PORT}
        volumes:
            - mysql_data:/var/lib/mysql

    gamespace_adminer:
        container_name: gamespace_adminer_dev
        image: adminer:latest
        environment:
            ADMINER_DEFAULT_SERVER: ${DB_HOST}
        ports:
            - ${ADM_HOST_PORT}:${ADM_DOCKER_PORT}
        links:
            - ${DB_HOST}
        depends_on:
            - ${DB_HOST}
        restart: always

volumes:
    mysql_data:
        driver: local
