services:
    gamespace_web:
        container_name: gamespace_web_prod
        build:
            context: .
            target: prod
        restart: always
        environment:
            DATABASE_URL: ${DATABASE_URL}
            WEB_HOST_PORT: ${WEB_HOST_PORT}
            WEB_URL_ROOT: ${WEB_URL_ROOT}
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        # ports:
        #     - ${WEB_HOST_PORT}:${WEB_DOCKER_PORT}
        networks:
            - traefik_default
        labels:
            - traefik.enable=true
            - traefik.http.routers.gamespace_www.entrypoints=websecure
            - traefik.http.routers.gamespace_www.tls=true
            - traefik.http.routers.gamespace_www.tls.certresolver=production
            - traefik.http.routers.gamespace_www.rule=Host(`gamespace.clement-jny.fr`) # ${DOMAIN}
            - traefik.http.services.gamespace_www.loadbalancer.server.port=${WEB_DOCKER_PORT}
        links:
            - ${DB_HOST}
        depends_on:
            - ${DB_HOST}

    gamespace_db:
        container_name: gamespace_db_prod
        image: mariadb:11.6.2
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            TZ: "Europe/Paris"
        ports:
            - ${DB_HOST_PORT}:${DB_DOCKER_PORT}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - traefik_default

    gamespace_adminer:
        container_name: gamespace_adminer_prod
        image: adminer:latest
        environment:
            ADMINER_DEFAULT_SERVER: ${DB_HOST}
        ports:
            - ${ADM_HOST_PORT}:${ADM_DOCKER_PORT}
        links:
            - ${DB_HOST}
        depends_on:
            - ${DB_HOST}
        restart: always
        networks:
            - traefik_default

volumes:
    mysql_data:
        driver: local

networks:
    traefik_default:
        external: true
