name: Prod Workflow - Deploy to production

on:
    # Runs on closed pull request targeting the main branch
    push:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    # Deployment job
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Connect to vps & run docker
              uses: appleboy/ssh-action@v1.2.1
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      git clone https://github.com/clement-jny/gamespace-devops.git
                      cd gamespace-devops
                      docker compose-f compose.prod.yml up --build -d
